/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ServiceRequest = IDL.Record({
  'customerName' : IDL.Text,
  'issueDescription' : IDL.Text,
  'modelNumber' : IDL.Text,
  'timestamp' : Time,
  'applianceType' : IDL.Text,
  'customerEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getContactByEmail' : IDL.Func([IDL.Text], [ContactForm], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ServiceRequest = IDL.Record({
    'customerName' : IDL.Text,
    'issueDescription' : IDL.Text,
    'modelNumber' : IDL.Text,
    'timestamp' : Time,
    'applianceType' : IDL.Text,
    'customerEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getContactByEmail' : IDL.Func([IDL.Text], [ContactForm], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };